### ISSUE TITLE
No playlist found with title "Daily Jams for <REDACTED>"

### ISSUE THREAD

**Issue by DeviantEng** [Mjsciarabba/Listenbrainz-Playlist-Sync#7]
Hi, first let me say that I've been looking for a script like this for a while and super excited to find this!  I use Plexamp, scrobble to LB, and so badly want the LB playlists that are auto-generated in Plexamp.

I set up your script using the docker image (had issues, but worked around them -- will share that feedback later in a separate issue).  This is the output I am receiving when the application runs:

2025-06-13,12:51:22 - INFO: Daily Jams for <REDACTED>
2025-06-13,12:51:22 - INFO: Getting playlists...
2025-06-13,12:51:23 - INFO: API call successful, parsing response...
2025-06-13,12:51:23 - ERROR: An error occurred: No playlist found with title "Daily Jams for <REDACTED>"

This is my current config.yml
```
# Plex Info
baseurl: '172.16.1.200:32400'
token: '<REDACTED>'
music_section: 'Music'
poster_file_path: ''
# filter_genre: 'YOUR_GENRE'
playlist_prefix: 'Listenbrainz '

# ListenBrainz Info
user_token: '<REDACTED>'
playlist_username: '<REDACTED>'
api_email: '<REDACTED>@gmail.com'
create_daily: False
create_weekly: True
```

So I am not expecting Daily playlists to generate, since I don't have any in LB.  But I still get that error, like it's searching for daily and since they aren't there, it's failing.  I found this [LB forum post](https://community.metabrainz.org/t/would-you-like-to-test-drive-our-first-recommendations-feature/626352) regarding daily jam playlists, and started following [troi-bot](https://listenbrainz.org/user/troi-bot/), so tomorrow I should see a Daily Jam playlist and hopefully this will start working.  However, I would expect this module to not fail if I am config to **not** create daily playlists.

**Comment by thecivvie** [comment]
Did that work for you? I am having the same issue

**Comment by DeviantEng** [comment]
> Did that work for you? I am having the same issue

I did manage to get it working, but had to follow the troi-bot to get Daily Jams playlists to generate.  Without the Daily Jams, the scripts would just error out on me.  I run docker swarm, and this is the stack file that worked:  

```
version: '3.9'

services:
  listenbrainz-playlist-sync:
    image: ghcr.io/mjsciarabba/listenbrainz-playlist-sync:edge
    environment:
      TZ: America/Kentucky/Louisville
    volumes:
      - '/mnt/data01/docker/music/listenbrainz-playlist-sync/config.yml:/app/config.yml:ro'
      - '/mnt/data01/docker/music/listenbrainz-playlist-sync/run.sh:/app/run.sh:ro'
      - '/mnt/data01/docker/music/listenbrainz-playlist-sync/logs:/app/logs'
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - default

networks:
  default:
    driver: overlay
    ipam:
      config:
        - subnet: 10.203.1.32/27
```

This is what my `config.yml` looked like:
```
# Plex Info
baseurl: 'https://ip:32400 # Replace 'YOUR_PLEX_URL' with the URL for your server
token: 'xxx' # Replace 'YOUR_USER_TOKEN' with your Plex token
music_section: 'Music' # Replace 'YOUR_SECTION_NAME' with the name of your music section
poster_file_path: '' # OPTIONAL, replace 'YOUR_FILE_PATH' with the filepath to a poster for the playlist
filter_genre: '' # OPTIONAL, replace 'YOUR_GENRE' with the genre you want to filter by (case-sensitive, one only).
playlist_prefix: 'Listenbrainz ' # playlists are "Weekly Jams" and "Daily Jams". If you want to put something in front to make them "A_Weekly Jams" or whatever, put it here. Leave it blank (two quotes '' ) to not use a prefix

# ListenBrainz Info
user_token: 'xxx-xxx-xxx-xxx-xxx' # Replace 'YOUR_USER_TOKEN' with your actual ListenBrainz user token
playlist_username: 'username' # Replace 'YOUR_USERNAME' with the username of the user whose playlists you want to sync
api_email: 'user@email.com' # Replace with the email you want to use for the Musicbrainz API
create_daily: False # Set to true if you want this ListenBrainz playlist to be synced
create_weekly: True # Set to true if you want this ListenBrainz playlist to be synced
```

Even though I'm setting `create_daily` to `False`, it still created the daily and errored out until I had the daily jam playlist in Listenbrainz, lol.

The entrypoint also didn't work for me, so I created `run.sh` and mapped it and had to do this to make it work:
```
#!/bin/sh
cd /app

while true
do
  LOGFILE="/app/logs/listenbrainz-$(date +%Y%m%d-%H%M%S).log"
  /usr/local/bin/python /app/main.py 2>&1 | tee -a "$LOGFILE"
  find /app/logs -name "listenbrainz-*.log" -type f -mtime +15 -delete
  sleep 43200
done
```


So all in all, yes it worked but it was a PITA.  Maybe I misunderstand something about how it's supposed to be used, and I had to jump through hoops to get it working.  

Ironically, I stopped using this earlier this week (after 2 months of silence on my Issue above) and created my own tool that would generate `Weekly Jams`, `Daily Jams`, and `Weekly Exploration` Listenbrainz playlists in my Plex, as well as creating a custom import list for Lidarr for artists from the `Weekly Exploration` playlist.  So here's my shameless plug to check it out (it's a provided docker container already, or you can run the app manually without docker):
https://github.com/DeviantEng/lb-lidarr-plex
